### ISSUE TITLE
  private $imgUrl should by   private $imageUrl;

### ISSUE THREAD

**Issue by meinmotion** [DevelopFer/active-campaign-v3-api-php#11]
The Product Image url is not set correctly. In the model ActiveCampaignOrderProduct **imgUrl** is used a an Private but this should be **imageUrl**

So line 18: 
private $imageUrl;

Line: 78 and 82 
        return $this->imageUrl;

**Comment by DevelopFer** [comment]
Hey @meinmotion thank you for your feedback, I just released the new version after changing the attribute from imgUrl to imageUrl.
