### ISSUE TITLE
Phone Contact need to be a String

### ISSUE THREAD

**Issue by abaticst** [DevelopFer/active-campaign-v3-api-php#14]
Hi, ActiveCampaign take the Phone like a String, not a Int.

Can you change it?

src/models/ActiveCampaignContact.php

[(https://developers.activecampaign.com/reference/create-a-new-contact)]

Regards

**Comment by DevelopFer** [comment]
I updated the type of the parameter expected; thank you for the heads up! hope it helps 👍
