### ISSUE TITLE
How to update a contact email?

### ISSUE THREAD

**Issue by zebrastribe** [DevelopFer/active-campaign-v3-api-php#5]
Hi
I need to update a contacts email...how?

BR,

**Comment by KiranSai7** [comment]
Did you find how to update @zebrastribe ??

**Comment by zebrastribe** [comment]
No. Sorry. Maybe this example can help:
https://github.com/DevelopFer/active-campaign-v3-api-php/blob/master/examples/contacts/CreateOrUpdateContact.php
